[loggers]
keys=root

[handlers]
keys=coloredHandler

[formatters]
keys=coloredFormatter

[logger_root]
level=INFO
handlers=coloredHandler

[handler_coloredHandler]
class=StreamHandler
level=INFO
formatter=coloredFormatter
args=(sys.stdout,)

[formatter_coloredFormatter]
class=ontocast.logging_utils.ColoredFormatter
format=%(asctime)s - %(levelname)s - %(name)s.%(funcName)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S 