[loggers]
keys=root

[handlers]
keys=richHandler

[formatters]
keys=richFormatter

[logger_root]
level=WARNING
handlers=richHandler

[handler_richHandler]
class=rich.logging.RichHandler
level=WARNING
formatter=richFormatter
args=()

[formatter_richFormatter]
format=%(name)s.%(funcName)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S 