[loggers]
keys=root

[handlers]
keys=richHandler

[formatters]
keys=richFormatter

[logger_root]
level=INFO
handlers=richHandler

[handler_richHandler]
class=rich.logging.RichHandler
level=INFO
formatter=richFormatter
args=()

[formatter_richFormatter]
format=%(message)s
datefmt=%Y-%m-%d %H:%M:%S 